/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Packet {
  buffer: Buffer
  address: string
  port: number
  version: number
}
export class Socket {
  address: string
  port: number
  /**
  * Creates a new Socket instance
  * @param address The address to bind to
  */
  constructor(address: string, port: number)
  /**
  * Listens and receives packets from the socket.
  */
  listen(incoming: (err: null | Error, result: Packet) => void, outgoing: (err: null | Error, result: Packet) => void): void
  /**
  * Closes the Socket instance.
  */
  close(): void
  send(buffer: Buffer, address: string, port: number, version: number): void
}
